{% set name = "hdf5plugin" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f6d886012c37bf7e8e002173dd6b16e6879b8e0e9f7d2f2ef9f79db97ed28d2

build:
  number: 1
  skip: true  # [win and py<30]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - hdf5
  run:
    - h5py
    - python

test:
  imports:
    - hdf5plugin

about:
  home: https://github.com/silx-kit/hdf5plugin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HDF5 Plugins for windows,MacOS and linux

extra:
  recipe-maintainers:
    - tschoonj
    - t20100
