{% set name = "hdf5plugin" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf78f1426b5868128b9ec6c498b70d6734e1dc8007a8ed1e7282954ab421b3fa

build:
  number: 1
  script_env:
    - HDF5PLUGIN_SSE2=True  # [x86]
    - HDF5PLUGIN_SSE2=False  # [not x86]
    - HDF5PLUGIN_SSSE3=False
    - HDF5PLUGIN_NATIVE=False
    - HDF5PLUGIN_AVX2=False
    - HDF5PLUGIN_AVX512=False
    - HDF5PLUGIN_BMI2=False
    - HDF5PLUGIN_OPENMP=False
    - HDF5PLUGIN_SYSTEM_LIBRARIES=blosc,blosc2,lz4,zlib,zstd

requirements:
  build:
    - pkg-config   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - hdf5
    - py-cpuinfo ==9.0.0
    - pkgconfig
    - blosc
    - c-blosc2
    - lz4-c
    - zlib
    - zstd
  run:
    - h5py >=3.0.0
    - python

test:
  imports:
    - hdf5plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silx-kit/hdf5plugin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HDF5 Plugins for windows, MacOS, and linux

extra:
  recipe-maintainers:
    - tschoonj
    - t20100
